[package]
name = "terra-rust"
version = "0.1.2"
authors = ["PFC-Validator <PFC-Validator@protonmail.com>"]
edition = "2018"
readme = "README.md"
homepage = "https://github.com/PFC-Validator/terra-rust/"
repository = "https://github.com/PFC-Validator/terra-rust/"
keywords = ["terra", "blockchain"]
categories = ["cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "terra-rust-api",
]
exclude = [

]
[dependencies]
terra-rust-api = { path = "./terra-rust-api", version = "0.1" }
error-chain = "0.12.2"
tokio = { version = "1.4", features = ["full"] }
structopt = "0.3"
env_logger = "0.8.3"
log="0.4"
serde = { version = "1.0", features = ["derive"] }
dotenv="0.15.0"
keyring = "0.10.1"
bitcoin="0.26.0"
serde_json = "1.0"
rust_decimal="1.12.2"
rust_decimal_macros="1.12.2"